version: '3.5'

services:
  mongodb:
    image: mongo
    container_name: mongodb-colligence
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  mariadb:
    image: mariadb:10.2
    container_name: mariadb-colligence
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/data/db
    ports:
      - 3306:3306
    networks:
      - backend

#  spring-boot-base:
#    image: .
#    container_name: api.colligence.io
#    depends_on:
#    - mongodb
#    - mariadb
#    ports:
#    - 8080:8080

volumes:
  mongo-data:
    name: mongo-colligence
    driver: local
  mysql-data:
    name: mysql-colligence
    driver: local

networks:
  backend:
    name: colligence-docker-network