spring:
  profiles:
    active: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 411922572522-amjb41f97ahgnbq06jiicm13pt33nrg6.apps.googleusercontent.com
            client-secret: NP3ICbi4VpnrAAdUS5aAgK4u
          facebook:
            client-id: ae1d08d5c1feb2b85d2f44387851a65d
            client-secret: vFvtWZfxo9sUR84xcuMhPXJvnXiAecJ4
          kakao:
            client-id: ae1d08d5c1feb2b85d2f44387851a65d
            client-secret: vFvtWZfxo9sUR84xcuMhPXJvnXiAecJ4
            authorization-grant-type: authorization_code
            redirect-uri-template: ${baseUrl}/oauth2/kakao/${registrationId}
            scope: profile
            client-name: KaKao
            client-authentication-method: POST
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    initialization-mode: always
  data:
    rest:
      base-path: /api
  jpa:
    ## 추후 DDL이 필요없을 경우 삭제. 초기 테스트/빌드 업 시에만 사용해볼 것.
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

# Actuator Setting
management:
  endpoints:
    enabled-by-default: true
    # [임시] use all for web
    web.exposure.include: "*"

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring_database
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/spring_database
    username: "root"
    password: "!@coLLiGEnce#$"
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://192.168.0.20:27017/spring_database
  datasource:
    url: jdbc:mariadb://192.168.0.20:3306/spring_database
    username: "root"
    password: "!@coLLiGEnce#$"
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver

#---
#spring:
#  profiles: prod
#  data:
#    mongodb:
#      uri: mongodb://spring_user:112233@192.168.0.20/spring_database
#      authentication-database: spring_database
#  datasource:
#    url: jdbc:mariadb://192.168.0.20:4306/spring_database
#    username: root
#    password: 112233
#    dbcp2:
#      driver-class-name: org.mariadb.jdbc.Driver

---
spring:
  profiles: docker-build
  data:
    mongodb:
      uri: mongodb://mongodb.local:27017/spring_database
  datasource:
    url: jdbc:mariadb://mariadb.local:3306/spring_database
    username: "root"
    password: "!@coLLiGEnce#$"
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
